# This docker-compose file is just here for testing
version: "3.4"

services:
  webapp:
    # build:
    #   dockerfile: docker/webapp.Dockerfile
    #   target: branded
    #   context: .
    # args:
    #   - APP_IMAGE=senderfm/webapp-branded:latest
    image: senderfm/webapp-branded:latest
    ports:
      - 3000:3000
    networks:
      - test-network
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - GRAPHQL_URI=http://backend:4000
      - MAPBOX_TOKEN="pk.eyJ1IjoiYnVzZmFrdG9yIiwiYSI6ImNraDNiM3JxcDBhaWQydG1uczhpZWtpOW4ifQ.7TNRTO-o9aK1Y6MyW_Nd4g"
      - WEBSOCKETS_URI=${WEBSOCKETS_URI}
      - PUBLIC_REGISTRATION=true
  backend:
    # build:
    #   dockerfile: docker/backend.Dockerfile
    #   target: branded
    #   context: .
    # args:
    #   - APP_IMAGE=senderfm/backend-branded:latest
    image: senderfm/backend-branded:latest
    networks:
      - test-network
    depends_on:
      - neo4j
    ports:
      - 4000:4000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - GRAPHQL_URI=http://backend:4000
      - CLIENT_URI=http://localhost:3000
      - JWT_SECRET=b/&&7b78BF&fv/Vd
      - MAPBOX_TOKEN=pk.eyJ1IjoiYnVzZmFrdG9yIiwiYSI6ImNraDNiM3JxcDBhaWQydG1uczhpZWtpOW4ifQ.7TNRTO-o9aK1Y6MyW_Nd4g
      - PRIVATE_KEY_PASSPHRASE=a7dsf78sadg87ad87sfagsadg78
      - EMAIL_SUPPORT=support@wir.social
      - EMAIL_DEFAULT_SENDER=info@wir.social
      - PUBLIC_REGISTRATION=true
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=mailserver
      - SMTP_PORT=25
      - SMTP_IGNORE_TLS=true
  neo4j:
    image: senderfm/neo4j-community-branded:latest
    networks:
      - test-network
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7687:7687
  mailserver:
    image: djfarrelly/maildev
    ports:
      - 1080:80
    networks:
      - test-network
networks:
  test-network: